CREATE OR REPLACE SCHEMA DEV_EDW.REFINED_CONTROL CLONE PROD_EDW.REFINED_CONTROL;
CREATE OR REPLACE SCHEMA DEV_RAW.RAW_EXAMPLE_2 CLONE PROD_RAW.RAW_EXAMPLE_2;
CREATE OR REPLACE SCHEMA DEV_RAW.RAW_EXAMPLE_1 CLONE PROD_RAW.RAW_EXAMPLE_1;