# Clone Env Example
name: replicate_prod

on:
  push:
    - ["feature_*"]
# More likley do a workflow dispatch -> 
  workflow_dispatch:
    

jobs:
  clone_prod:
    env:
      SNOWFLAKE_USER: "${{ secrets.SNOWFLAKE_USER }}"
      SNOWFLAKE_PK: "${{ secrets.SNOWFLAKE_PK }}"
      SNOWFLAKE_ACCOUNT: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
      SNOWFLAKE_WAREHOUSE: "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
      SNOWFLAKE_ROLE: "${{ secrets.SNOWFLAKE_ROLE }}"
      SNOWFLAKE_DATABASE: "${{ secrets.SNOWFLAKE_DATABASE }}"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cicd/requirements.txt

    - name: Run Snowflake Clone CI/CD
      run: |
        python cicd/cicd_helper.py


